# ANUS Configuration File
llm:
  provider: openai
  api_key: "${OPENAI_API_KEY}"
  model: gpt-4o

# 선택 사항: 다른 제공자 구성
anthropic:
  api_key: your_anthropic_api_key

# 선택 사항: 도구별 설정 구성
browser:
  headless: true


model:
  provider: openai
  name: gpt-4
  api_key: "${OPENAI_API_KEY}"  # Uses the environment variable you set

agent:
  name: anus
  mode: auto  # Changed from multi to auto
  max_iterations: 10
  memory_capacity: 2000
  verbose: true

tools:
  enabled:
    - calculator
    - search
    - text
    - code

logging:
  level: DEBUG
  file: logs/anus.log 